# Generated by Django 5.2.1 on 2025-05-15 06:11

import django.db.models.deletion
import user.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public identifier')),
                ('profile_pic', models.FileField(blank=True, null=True, upload_to=user.models.custom_filename)),
                ('name', models.CharField(max_length=100)),
                ('cell_number', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role_id', models.CharField(choices=[('ADMIN', 'Admin'), ('NORMAL', 'Normal User')], default='NORMAL', max_length=20)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token identifier')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('ttl', models.BigIntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to='user.user')),
            ],
            options={
                'verbose_name': 'access token',
                'verbose_name_plural': 'access tokens',
            },
        ),
    ]
